pebble-extension/package.json, pebble-extension/src/browser/commands.ts, pebble-extension/src/browser/core.ts, pebble-extension/src/browser/widget/drag.ts, pebble-extension/src/common/api.ts
multiple collections/files upload is working now on the frontend, if one file is selected, it uses the usual `document:put` method, if it's a folder, or more than one item, it will send a multipart form to another endpoint (`documents` for now)
=> Files upload

README.md, pebble-extension/src/browser/core.ts, pebble-extension/src/common/templates/rng.ts, pebble-extension/src/common/templates/xslt.ts
- changed defaults for Schematron and XSLT templates
- show progress while uploading
- updated readme
=> small fixes

pebble-extension/package.json, pebble-extension/src/browser/dialogs/_dialog.scss, pebble-extension/src/browser/dialogs/properties-dialog.ts, pebble-extension/src/browser/dialogs/user-dialog.ts, pebble-extension/src/browser/style/_keys.scss, pebble-extension/src/browser/style/index.scss, pebble-extension/src/classes/autocomplete.ts
"primary group" field in user properties, and "owner" and "group" fields in document/collection properties are now auto-complete lists
=> added autocomplete field

pebble-extension/package.json, pebble-extension/src/browser/commands.ts, pebble-extension/src/browser/contribution.ts, pebble-extension/src/browser/core.ts, pebble-extension/src/browser/dialogs/connection-dialog.ts, pebble-extension/src/browser/widget/home.tsx, pebble-extension/src/browser/widget/main.tsx, pebble-extension/src/browser/widget/toolbar.tsx, pebble-extension/src/classes/connection.ts
Mostly just renaming and capitalizing some things.
I also bumped up some dependency versions.
=> Small changes

.travis.yml, appveyor.yml, browser-app/package.json, cypress.json, electron-app/package.json, fusion-studio-extension/package.json, fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/browser/dialogs/properties-dialog.ts, fusion-studio-extension/src/browser/resource.ts, package.json
I am sending this as a separate PR as I want to make sure that CI passes on AppVeyor and Travis.
=> Fix the CI builds

.travis.yml, cypress/integration/tree_spec.js
See also https://github.com/evolvedbinary/fusion-studio-api/issues/12
=> Fix the version of 3rd-party resources used in CI

README.md
Add a badge which shows the latest version published to npmjs.com.
=> Add npmjs version badge

fusion-studio-extension/src/browser/dialogs/_dialog.scss, fusion-studio-extension/src/browser/dialogs/_permissions-editor.scss, fusion-studio-extension/src/browser/dialogs/group-dialog.ts, fusion-studio-extension/src/browser/dialogs/user-dialog.ts, fusion-studio-extension/src/browser/style/_button.scss, fusion-studio-extension/src/browser/style/_checkbox.scss, fusion-studio-extension/src/browser/style/_keys.scss, fusion-studio-extension/src/browser/style/_tabs.scss, fusion-studio-extension/src/browser/widget/_eval.scss, fusion-studio-extension/src/browser/widget/_home.scss, fusion-studio-extension/src/browser/widget/_toolbar.scss, fusion-studio-extension/src/browser/widget/_tree.scss, fusion-studio-extension/src/browser/widget/_welcome.scss, fusion-studio-extension/src/browser/widget/eval.tsx, fusion-studio-extension/src/classes/dialog-field.ts
=> updating more styles

cypress/integration/eval_panel.js, fusion-studio-extension/src/browser/widget/eval.tsx
=> fix: undefined function halted the rendering of evaluation panel

cypress/integration/tree_spec.js, fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/browser/dialogs/properties-dialog.ts
=> Deprecated tree

fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/classes/error.ts, fusion-studio-extension/src/common/api.ts
=> check api version before connecting

fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/browser/dialogs/basic.ts, fusion-studio-extension/src/browser/widget/eval.tsx
=> Better error handling for evaluating XQuery

cypress/integration/operations_spec.js, cypress/integration/properties.js, cypress/support/index.d.ts, cypress/support/utils.js, fusion-studio-extension/src/browser/commands.ts, fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/browser/dialogs/properties-dialog.ts, fusion-studio-extension/src/browser/dialogs/user-dialog.ts, fusion-studio-extension/src/classes/autocomplete.ts, fusion-studio-extension/src/classes/template.ts, fusion-studio-extension/src/common/templates/restxq.ts, fusion-studio-extension/src/common/templates/rng.ts, fusion-studio-extension/src/common/templates/xml.ts, fusion-studio-extension/src/common/templates/xq.ts, fusion-studio-extension/src/common/templates/xqm.ts, fusion-studio-extension/src/common/templates/xsd.ts, fusion-studio-extension/src/common/templates/xslt.ts
- fix a bug that always tries to rename an object after closing the properties dialog
- improved the autocomplete input component
- visual improvement for the properties dialog
- added more helper functions to cypress
- added tests for the properties dialog
=> Properties dialog

README.md
=> Yarn should be installed via NPM - correct the README.md

fusion-studio-extension/src/browser/widget/_eval.scss, fusion-studio-extension/src/browser/widget/eval.tsx, fusion-studio-extension/src/common/api.ts
Added an option to properly indent the result
Related to: https://github.com/evolvedbinary/fusion-studio-extension/issues/194
=> Formatting XQuery evaluation result

.travis.yml
Update to fusion-studio-api-1.1.1
=> Update to latest API for CI tests

fusion-studio-extension/src/browser/dialogs/alert-dialog.ts, fusion-studio-extension/src/browser/widget/eval.tsx, fusion-studio-extension/src/classes/error.ts, fusion-studio-extension/src/common/api.ts
Added an error message for failed XQuery evaluation
Related to: #216
=> Error handling

cypress/integration/properties.js, fusion-studio-extension/src/browser/commands.ts, fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/common/api.ts
* added server info dialog
* fixed a bug where RestXQ endpoints, Users, Groups, and Indexes are gone after updating connection's properties
Closes https://github.com/evolvedbinary/fusion-studio-extension/issues/214
=> Connections list improvements

browser-app/package.json, cypress/integration/properties.js, electron-app/package.json, fusion-studio-extension/package.json, fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/browser/widget/main.tsx, yarn.lock
Changes on toolbar's size don't reflect on the UI immediately which leads to confusing UI shifts.
=> Nodes height

browser-app/package.json, electron-app/package.json, fusion-studio-extension/package.json, yarn.lock
- Theia: 1.5.0 => 1.7.0
- Moment js: 2.27.0 => 2.29.1
- Electron: 9.2.1 => 9.3.4
=> Theia upgraded to 1.7.0

.travis.yml, cypress/integration/api.js, cypress/integration/eval_panel.js, cypress/integration/operations_spec.js, cypress/integration/properties.js, cypress/integration/tree_spec.js, cypress/plugins/index.js, cypress/support/config.js, cypress/support/index.js, cypress/support/utils.js
Test against multiple FusionDB and eXist-db versions
=> Further Cypress targets

browser-app/package.json, cypress/integration/operations_spec.js, cypress/integration/properties.js, cypress/integration/tree_spec.js, cypress/support/config.js, cypress/support/utils.js, electron-app/package.json, fusion-studio-extension/package.json, fusion-studio-extension/src/browser/commands.ts, fusion-studio-extension/src/browser/core.ts, fusion-studio-extension/src/browser/dialogs/properties-dialog.ts, fusion-studio-extension/src/browser/widget/drag.ts, fusion-studio-extension/src/browser/widget/eval.tsx, fusion-studio-extension/src/browser/widget/main.tsx, fusion-studio-extension/src/classes/node.ts, yarn.lock
- Renaming items now update them instead of recreating them
- Updated tests for inline renaming
- Added inline renaming for connections
- Added tests for renaming and deleting connections, and for connections properties dialog
=> Improved renaming items in the tree

browser-app/package.json, electron-app/package.json, fusion-studio-extension/package.json, package.json, yarn.lock
- fusion-studio-extension: 1.1.0 ==> 1.2.0
- theia: 1.9.0 ==> 1.11.0
- cypress: 6.2.0 ==> 6.6.0
- mime-types: 2.1.27 => 2.1.29
=> Updated dependencies

.clabot
=> Add Younes Bahloul to CLA

.circleci/config.yml, README.md, cypress/integration/01_connection_spec.js, cypress/integration/04_document_spec.js, cypress/integration/properties.js, cypress/support/utils.js, package.json, yarn.lock
add property dialog tests for documents and connections
add test prevent duplicate document creation
=> E2e rewrite 2
